pipeline:
  - name: analysis
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - /root/entrypoint.sh
      - sbt -ivy ./.ivy2 dependencyCheck
      - sbt scalastyle | true
      - sbt scapegoat | true
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_artifactory
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push

  - name: sonar-scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER}
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - ${DRONE_BRANCH}
      event:
        - push
    depends_on:
      - analysis

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
    - /root/entrypoint.sh
    - sbt docker:stage
    environment:
    - ARTIFACTORY_USERNAME=drt_artifactory
    secrets:
    - ARTIFACTORY_PASSWORD
    when:
      event:
      - push
      branch:
      - ${DRONE_BRANCH}

  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-analytics
    build_args:
    - APP_BUILD=${DRONE_COMMIT_SHA}
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
